OpenGraph tags
shoggoth-systems/shoggoth pull request #30
Opened 2023-11-15 10:01 UTC by samsararider

Here's how it looks in Discord:

![1](https://github.com/shoggoth-systems/shoggoth/assets/150008495/de1850ae-efbb-473d-ac67-a09cf600c0a2)
![2](https://github.com/shoggoth-systems/shoggoth/assets/150008495/2a129dba-3b1d-4b11-8b9d-a5705f1306b4)
![3](https://github.com/shoggoth-systems/shoggoth/assets/150008495/8ad261c2-86f9-4c1a-88bb-19e65144c36a)
![4](https://github.com/shoggoth-systems/shoggoth/assets/150008495/9137988c-62be-4a2b-bac2-04d40c7aacc2)
![5](https://github.com/shoggoth-systems/shoggoth/assets/150008495/9b0f9fd4-da5d-473a-8add-0a7d543a2833)
![6](https://github.com/shoggoth-systems/shoggoth/assets/150008495/5be31cc0-f0d1-4459-afcd-dfcd131d2855)
![7](https://github.com/shoggoth-systems/shoggoth/assets/150008495/780dd03e-d9cb-4dc4-9ac2-13ab5dd5ea61)
![8](https://github.com/shoggoth-systems/shoggoth/assets/150008495/2f20b76b-25f9-4aa5-b1f8-bd8d1414a313)
![9](https://github.com/shoggoth-systems/shoggoth/assets/150008495/15a75c71-456f-4057-bbf3-234e4f15a999)

Requires ImageMagick to compile.

Tested on macOS 14 with ImageMagick 7 and on Ubuntu 22.04 with ImageMagick 6.

I haven't run address sanitizer.

I was on the lookout for boundary overruns and memory leaks, I don't think there are any.

Lmk if it looks allg.

2023-11-16 13:52 UTC, samsararider commented
@thenetrunna 
1. resource path in title:
![tags](https://github.com/shoggoth-systems/shoggoth/assets/150008495/8a948965-0ba0-41cb-96c0-deb2f9a39dc4)
2. ellipsis on text overflow:
![alksjdlkajsdlkajsdlkjasdlkjaslkdj](https://github.com/shoggoth-systems/shoggoth/assets/150008495/a62f2e63-87b7-4e44-a728-36fb16e88194)
3. og card for canonical url:
![1](https://github.com/shoggoth-systems/shoggoth/assets/150008495/39e49bd6-4f35-4006-8441-825830b377b9)

2023-11-21 18:19 UTC, thenetrunna requested changes

2023-11-21 18:19 UTC, thenetrunna commented on src/node/og/og.c
> +#define FONT_FILEPATH "./node/explorer/static/font/Roboto-Regular.ttf"
The paths should not be hardcoded.
Use utility functions to obtain the explorer path, then append the relative paths.

2023-11-21 21:10 UTC, thenetrunna commented
Replaced by #34

2023-11-21 21:10 UTC, closed without merging